version: '2'

services:
  app:
    build: .
    ports:
      - '5555:5555'
    volumes:
      - .:/usr/src/app
      # prevents host/container contamination
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
    command: npm run dev

  # redis:
  #   image: redis:4.0.5-alpine
  #   command: ["redis-server", "--appendonly", "yes"]
  #   hostname: redis
  #   networks:
  #     - redis-net
  #   volumes:
  #     - redis-data:/data